language: ruby
rvm:
- 2.5.3
- 1.9.3
- jruby-19mode
- rbx-2
services:
  - postgresql
test:
  adapter: postgresql
  database: travis_ci_test
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec